-- AlterTable
ALTER TABLE `permission` MODIFY `permission` ENUM('LOGIN', 'LOGOUT', 'REQUEST_CLAIM', 'ASSIGN_CLAIM', 'GET_USER_CLAIMS', 'GET_SELF_CLAIMS', 'PAGE_PERMISSION_REIMBURSEMENT', 'PAGE_PERMISSION_REIMBURSEMENT_DASHBOARD', 'PAGE_PERMISSION_REIMBURSEMENT_MANAGE_CLAIM', 'PAGE_PERMISSION_CYPRESS_REPORT') NOT NULL;
